### ISSUE TITLE
l can add CN language

### ISSUE THREAD

**Issue by 050223** [pierre-josselin/payday-2-ultimate-trainer-5#10]
l am working on to translate it as chinese, so how to add it?

**Comment by pierre-josselin** [comment]
Hi,

Considering that you are not familiar with Git/GitHub, here is a simplified and detailed method :

- Rename your file to _chs.json_ for simplified chinese or _cht.json_ for traditional chinese
- Fork the [5.2.0 branch](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/tree/5.2.0) of the project (by clicking the "Fork" button)
- Go to your forked repository then navigate to the _locales_ folder
- Click on the "Add files" button then on "Upload files"
- Upload your locale file
- Add a commit title like "Add chinese locale"
- Make sur "Commit directly to the 5.2.0 branch." is selected
- Click the "Commit changes" button
- Click on "Contribute" next to "This branch is 1 commit ahead of pierre-josselin:5.2.0."
- Follow steps to create a pull request

**Comment by 050223** [comment]
okay so l will translate it as soon as l can lol

**Comment by 050223** [comment]
Can we add discord to communicate with each other? ArtemisFowl#2901 THX

**Comment by pierre-josselin** [comment]
Ok, thank you for that !

Here is the original english file : [en.json](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/blob/5.2.0/locales/en.json)

But please keep the formatting of the file (line breaks, translations order...)

**Comment by pierre-josselin** [comment]
> Can we add discord to communicate with each other? ArtemisFowl#2901 THX

I would prefer Steam, you can add me here : 
https://steamcommunity.com/id/childofsorrow3
