### ISSUE TITLE
Can't stop bags/loot?

### ISSUE THREAD

**Issue by EliteBiker** [pierre-josselin/payday-2-ultimate-trainer-5#100]
Spawn sets don't work or how to use?
I press on a set and nothing happens. And Menu could maybe have a better Visual View on the what things to spawn, It could really help 👍 

Any tutorials?

**Comment by pierre-josselin** [comment]
Hi, once you have selected the spawn set you want, use the mouse scroll up & down to select the unit to spawn and spawn it with mouse wheel button. You can change theses binds in the "mod keybinds" menu.
