### ISSUE TITLE
Add X ray to items like the goats or items 

### ISSUE THREAD

**Issue by esteban142536** [pierre-josselin/payday-2-ultimate-trainer-5#101]
The X-ray function shout be able to see items like goats, chemistry, or wood planks, also should toggle between the items or the enemies

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
