### ISSUE TITLE
Add more enemies/allies (like the shield that flashes you etc.)

### ISSUE THREAD

**Issue by Thepaydayman** [pierre-josselin/payday-2-ultimate-trainer-5#104]

**Comment by pierre-josselin** [comment]
Hi, since I'm no longer actively working on this mod this will not be planned but I'll leave the issue open if anyone wants to do it.

**Comment by Thepaydayman** [comment]
Ah, it's fine then, i'm gonna wait for someone.

**Comment by Thepaydayman** [comment]
> Hi, since I'm no longer actively working on this mod this will not be planned but I'll leave the issue open if anyone wants to do it.

Hey, i found the list of all the new and old and more powerful enemies, and i want to know where is the list of enemies i can spawn so i can modify it.

**Comment by pierre-josselin** [comment]
Hi, this is here:

https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/blob/main/UltimateTrainer5/classes/Tables.lua#L131

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
