### ISSUE TITLE
protection

### ISSUE THREAD

**Issue by Rrhyast** [pierre-josselin/payday-2-ultimate-trainer-5#20]
some %$$ users can detect that you're using hacks and they start griefing with slowmo and other stuff and its so annoying.

**Comment by pierre-josselin** [comment]
By enabling the "Hide mods list" option from the "configuration menu", other players cannot see what mods you are using.

**Comment by Rrhyast** [comment]
> By enabling the "Hide mods list" option from the "configuration menu", other players cannot see what mods you are using.

the problem is the skill points that people able to see, and they're mad cuz everything maxed out xD

**Comment by pierre-josselin** [comment]
I see. I don't think I could do anything about that unfortunately.
