### ISSUE TITLE
HP decrease every time when joining the game 

### ISSUE THREAD

**Issue by Rrhyast** [pierre-josselin/payday-2-ultimate-trainer-5#22]
https://i.postimg.cc/pTGHHfvT/payday2-win32-release-0-FFm-YIjs8o.jpg

don't know why

**Comment by pierre-josselin** [comment]
For your information, this is due to the Frenzy skill :

> Basic (4 pt): You only get 30% of your maximum health and cannot heal above it but you take 10% less damage and healing received is reduced by 75%.
> Ace (8 pt): Damage taken is now reduced by 25% and healing received is reduced by 0%.

[Reference](https://payday.fandom.com/wiki/Frenzy)
