### ISSUE TITLE
Crash related to bag spawn

### ISSUE THREAD

**Issue by pierre-josselin** [pierre-josselin/payday-2-ultimate-trainer-5#31]
When a client picks up a bag that is not supposed to exist on a map, it seems to crash the host's game.

**Comment by Uziel2021** [comment]
this is a general issue of the game, if a player picks up a bag from the ground in a map where it is not supposed to exist, the game will attempt to show the 3d model of that bag in your back, which does not exist and if a player tries to process the action, they will crash. there is no solution to this issue as patching the bug on your client will not prevent it on other peers.

To prevent your game from ever crashing to this bug, you have to remove the 3d model rendering from your client, this can be done by removing the callback of `set_visual_carry` inside of `PlayerManager.set_synced_carry`
https://github.com/steam-test1/Payday-2-LuaJit-Source-With-Line-Numbers-Continued/blob/c02b01fdaa27e1c4264b4dd3393499770e0ae7b2/lib/managers/playermanager.lua#L3198

```lua
-- Lines 3014-3035
function PlayerManager:set_synced_carry(peer, carry_id, multiplier, dye_initiated, has_dye_pack, dye_value_multiplier)
	local peer_id = peer:id()
	self._global.synced_carry[peer_id] = {
		carry_id = carry_id,
		multiplier = multiplier,
		dye_initiated = dye_initiated,
		has_dye_pack = has_dye_pack,
		dye_value_multiplier = dye_value_multiplier
	}
	local character_data = managers.criminals:character_data_by_peer_id(peer_id)

	if character_data and character_data.panel_id then
		managers.hud:set_teammate_carry_info(character_data.panel_id, carry_id, managers.loot:get_real_value(carry_id, multiplier))
	end

	managers.hud:set_name_label_carry_info(peer_id, carry_id, managers.loot:get_real_value(carry_id, multiplier))
end
```

**Comment by pierre-josselin** [comment]
Thank you for the detailed information.

Remove the 3d model rendering from me will prevent other peers to crash?

**Comment by Uziel2021** [comment]
No, each time someone pick up a bag they receive a callback for `UnitNetworkHandler:sync_carry` which calls `PlayerManager:set_synced_carry`, unless they have the function modded to not display the 3d model, they will crash.

**Comment by pierre-josselin** [comment]
Ok !
