### ISSUE TITLE
Ultimate Suggestions!

### ISSUE THREAD

**Issue by Rrhyast** [pierre-josselin/payday-2-ultimate-trainer-5#48]
Hey man hope you're doing well! I know u know about p3dhack, but there is a lots of cool options in this hack that u can add it to 
 ultimate trainer! it saves a lots of time instead of suggest ideas one by one everyday and wasting a lots of time.

This one is trial version and a lots of functions locked behind paywall but u can see the name of the options and description of it:
[P3DHack Free 4.07.zip](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/files/8430312/P3DHack.Free.4.07.zip)

This one is standalone x-ray version:
[P3D X-Ray v1.7.zip](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/files/8430317/P3D.X-Ray.v1.7.zip)

**Comment by pierre-josselin** [comment]
Hi man, thanks for your interest in ultimate trainer, I'll look into it if it gives new ideas for features to add.

Of course I wouldn't add any proprietary code (and if possible, a code not developed by me or by a contributor).

I think the limits are not the ideas but the development, I'm working on it almost alone, for free and on my free time.
But I will continue to update when possible with ideas from the community!
