### ISSUE TITLE
Crashing with hide mods list

### ISSUE THREAD

**Issue by Moa-Kikuchi** [pierre-josselin/payday-2-ultimate-trainer-5#53]
When the "hide mods list" option is selected, I can't join a public game or create an offline game. As soon as I get to the mission briefing menu, the game crashes.

**Comment by pierre-josselin** [comment]
> > Hi Moa, I'll check that on next dev session. Can you share your _crash.txt_ file located at _%localappdata%/PAYDAY 2_ if possible ?
> 
> I can! It will be about 15 mins before I can, but I will as soon as possible! Thank you for the quick reply!

Thank you, don't worry, it's not urgent, I can't fix it right now anyway

**Comment by Moa-Kikuchi** [comment]
Unfortunately, Payday doesn't create a crash log for Linux so there's not too much I can give you... I can explain what happened real quick though!

I was running UT5 v2.0 since it first came out. 
A few days after using it, I started using the "Hide Mods List" option. 
About a week after having Hide Mods List enabled, my game started crashing whenever I tried to create or join a game offline or online.
I noticed removing UT5 fixed the issue so I started playing a bit without it. No issues.
Once reinstalling UT5, I figured out disabling hide mods list and reinstalling fixed the crashing issue.
Once re-enabling hide mods list after restarting with it off, it no longer crashes and I can't reenact the crashing.

I'm sorry I couldn't be of any help with the crashlog and if there's not much you can do about it, I completely understand! Just thought it would be a good idea to bring it up with you. For all I know, it might be an issue with Proton (Steams software to run Windows games on Linux). I appreciate your time and the time you've put into this mod!

Thank you.
Moa

**Comment by pierre-josselin** [comment]
@Moa-Kikuchi 

Thank you for the informations!

I tried to reproduce the problem but my game did not crash.

Don't worry about the crash log, I'll leave the issue open so that if someone also had the problem and uses Windows, they can share it.

Also, a crash when trying to join lobby could happen if:

- You have enabled the DLC unlocker
- You have equipped a weapon modification, mask pattern etc... from a DLC you don't own
- You have disabled the DLC unlocker

**Comment by Moa-Kikuchi** [comment]
Thank you. This is really embarassing, but I found out the problem had nothing to do with UT5 but my graphics settings. 

I'll go ahead and close the thread now. Super sorry. :(

**Comment by pierre-josselin** [comment]
@Moa-Kikuchi 

No problem, glad your issue is resolved!
Thank you for your interest in this mod.
