### ISSUE TITLE
No option for Mod

### ISSUE THREAD

**Issue by nabvbl** [pierre-josselin/payday-2-ultimate-trainer-5#58]
why there is no option for ultimate trainer 5?is the files that i put is correct?

![mods 7_5_2022 4_22_00 PM](https://user-images.githubusercontent.com/105102833/167245891-e3355816-b91d-4ed2-901d-92f0dc0322a6.png)
![PAYDAY 2 7_5_2022 4_22_54 PM](https://user-images.githubusercontent.com/105102833/167245896-987e4b0c-af23-4062-9b46-df9e20a39501.png)

**Comment by pierre-josselin** [comment]
Your "mods" folder should look more like this:

![image](https://user-images.githubusercontent.com/70814177/167455077-d7475a49-5230-445a-8975-9c4e5ec54d04.png)
