### ISSUE TITLE
How to hide Ultimate Trainer 5

### ISSUE THREAD

**Issue by ViniciusFXavier** [pierre-josselin/payday-2-ultimate-trainer-5#59]
### Some people use simple mods that as soon as they detect a few words from their installed mods they automatically kick you.
1. Change the file `mod.txt`
    1. In line 2 where is `"name": "Ultimate Trainer"` change to the name of another mod for example `"name": "Extra Heist Info"`
    2. In line 3 where is `"description": "Ultimate Trainer"` change to the description of another mod for example `"description": "[EHI] Shows trackers for various heist related gameplay elements"`
    3. In line 4 where is `"author": "Pierre Josselin"` change to the author of another mod for example `"author": "Dom"`
    4. In line 5 where is `"version": "5.2.0"` change to the version of another mod for example `"version": "1.3.2"`

---
### Use this mods can help:
- Hide Cheater Label - https://modworkshop.net/mod/31084

---
### Create a mod to hide mods message:

- `Script.lua`
```lua
function MenuCallbackHandler:is_modded_client()
    return false
end
 
function MenuCallbackHandler:is_not_modded_client()
    return true
end
 
function MenuCallbackHandler:build_mods_list()
    return {}
end
```

- `mod.txt`
```json
 {
	"name": "UI CSGo",
	"description": "Change UI to CSGo UI.",
	"author": "Newbie",
	"version": "1.0.0",
	"blt_version" : 2,
	"hooks": [
		{
			"hook_id": "lib/managers/menumanager",
			"script_path": "Script.lua"
		}
	]
}
```

**Comment by pierre-josselin** [comment]
Hi, thanks for sharing.

Doesn't [this commit](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/commit/6d85e98cb5439460defd5e30cb32eb05a7d18983) fixes the problem you describe ?

You can access this feature in **Configuration menu > Hide mods list**.

**Comment by ViniciusFXavier** [comment]
@pierre-josselin Thanks for replying, I believe that is enough.

I think maybe this implementation will help too.
It only shows the active mods and different of the ultimate trainer.

```lua
local build_mods_list_original = MenuCallbackHandler.build_mods_list
function MenuCallbackHandler:build_mods_list()
	local mods = {}
	if self:is_modded_client() then
		local BLT = rawget(_G, "BLT")

		if BLT and BLT.Mods and BLT.Mods then
			for _, mod in ipairs(BLT.Mods:Mods()) do
				if mod:IsEnabled() and mod:GetName() ~= "Ultimate Trainer" then
					local data = {
						mod:GetName(),
						mod:GetId()
					}

					table.insert(mods, data)
				end
			end
		end
	end

	return mods
end
```

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
