### ISSUE TITLE
Unlock Weapons doesn't truly unlock all weapons.

### ISSUE THREAD

**Issue by ren-mikkan** [pierre-josselin/payday-2-ultimate-trainer-5#65]
Well title says it all. It appears it doesn't unlock the galant rifle and mp40. Pretty sure it's because the guns are through side jobs, so maybe a option to complete all side jobs instantly or something like that would be good. Or just have unlock all weapons do that for you. 

![image](https://user-images.githubusercontent.com/106497085/173301591-648a2250-fd72-4020-93a4-ae55494d9b6e.png)

![image](https://user-images.githubusercontent.com/106497085/173301681-539bc25e-966c-4019-b346-fdfffc6aeaea.png)

**Comment by pierre-josselin** [comment]
Thanks for sharing this issue.

A side job clear option is planned: #32

**Comment by pierre-josselin** [comment]
Uziel2021 fixed it, changes are in main branch.
