### ISSUE TITLE
ultimate trainer 5 

### ISSUE THREAD

**Issue by chanouGTX** [pierre-josselin/payday-2-ultimate-trainer-5#75]
Bonjour/Bonsoir,

j'ai tout fais comme demander c'est a dire enlever le skip de l'intro du jeu et je l'ai mis dans les fichier payday2/mod mais cela ne fonctionne pas. Alors j'aurais besoin de conseil s'il vous plait pour que la prochaine fois marche correctement. 

Merci de votre attention,
bonne journée/bonne soirée

**Comment by pierre-josselin** [comment]
Bonjour, est-ce que tu as bien extrait l'archive et déplacé le dossier "UltimateTrainer5" dans le dossier "mods" ?

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
