### ISSUE TITLE
PayDay2 Update Pigs

### ISSUE THREAD

**Issue by Thx33** [pierre-josselin/payday-2-ultimate-trainer-5#77]
Hello. Will the pig money bag spawn trainer be updated?

**Comment by pierre-josselin** [comment]
Hi, there is a new type of bag ?

**Comment by Thx33** [comment]
Yes. Piggy Bucks bags

**Comment by pierre-josselin** [comment]
Ok yes i could add it easily as soon as the bag id is found

**Comment by Thx33** [comment]
how can i help with this?

**Comment by pierre-josselin** [comment]
You can ask for the bag name on [unknowncheats](https://www.unknowncheats.me/forum/payday-2-a/) if you want, i don't know how to get it since the [payday 2 source repository](https://github.com/mwSora/payday-2-luajit) is no longer updated.

**Comment by Thx33** [comment]
I wanted to find new bags myself. But can't open new .bundle files

**Comment by pierre-josselin** [comment]
Oh ok, let's hope someone can decompile the latest versions, unfortunately I can't do that.Le 13 août 2022 13:45, Thx33 ***@***.***> a écrit :
I wanted to find new bags myself. But can't open new .bundle files

**Comment by thignus** [comment]
You can use this to spawn the bag at the player's location.

```
local position = UT:getPlayerCameraPosition()
local rotation = UT:getPlayerCameraRotation()
local forward = UT:getPlayerCameraForward()
	
UT:spawnUnit(Idstring("units/pd2_dlc_pda9/props/pda9_pickup_feed_bag/pda9_pickup_feed_bag"), position, rotation)
```

To spawn more at once, change 100 with the amount you want
```
local position = UT:getPlayerCameraPosition()
local rotation = UT:getPlayerCameraRotation()
local forward = UT:getPlayerCameraForward()

for i = 0,100,1 do 
    UT:spawnUnit(Idstring("units/pd2_dlc_pda9/props/pda9_pickup_feed_bag/pda9_pickup_feed_bag"), position, rotation)
end
```

**Comment by pierre-josselin** [comment]
@thignus PR merged into main.

And thank you @holysnipz for sharing this up to date decompile.

**Comment by thignus** [comment]
@pierre-josselin  Just a note, unless for some reason they keep the piggy bags in the game once the event is over, be prepared to revert this change or keep it on a different branch for reference when they do another event

**Comment by pierre-josselin** [comment]
@thignus Ok!
