### ISSUE TITLE
Menu not opening

### ISSUE THREAD

**Issue by TinyCoderJay** [pierre-josselin/payday-2-ultimate-trainer-5#79]
I have tried everything, I have Micrsoft VC++ 2008 through 2019 installed and the menu won't open. I have SuperBLT updated, I have ultimate trainer 5 updated, I cannot see the options for it in the main menu under options, and click F1 in game does nothing.
![image_2022-08-20_153318554](https://user-images.githubusercontent.com/69621970/185763434-59a487f2-5631-4605-b3b2-58f6ee92f817.png)

**Comment by pierre-josselin** [comment]
Hi, in you "mods" folder, you should see the "UltimateTrainer5" folder. But it's not a subfolder of "payday-2-ultimate-trainer-5-5.3.0" that's why it don't works.

**Comment by TinyCoderJay** [comment]
> Hi, in you "mods" folder, you should see the "UltimateTrainer5" folder. But for now it's a subfolder of "payday-2-ultimate-trainer-5-5.3.0" that's why it don't works.

So how would I make this work? rename it to UltimateTrainer5?

**Comment by TinyCoderJay** [comment]
I also see no option for the trainer in the PD2 mod options, I only see my HUD module listed. @pierre-josselin. Any fix to this?

**Comment by TinyCoderJay** [comment]
**I HAVE FIXED THIS ISSUE** YOU MUST GO INSIDE THE payday-2-ultimate-trainer-5-5.3.0 AND TAKE OUT THE UltimateTrainer5 FOLDER AND PUT THAT IN YOUR MODS FOLDER
