### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by TinyCoderJay** [pierre-josselin/payday-2-ultimate-trainer-5#81]
Instead of having to keep clicking a button to spawn bags, make it to where you can hold the button and it will just spray them. Also if possible make a feature where you can delete the guards or civs without killing or having to answer pagers.

**Comment by pierre-josselin** [comment]
Thanks for the interesting suggestions. For now there is an option "Remove NPCs" which allows to "delete" both guards and civilians.

**Comment by TinyCoderJay** [comment]
> Thanks for the interesting suggestions. For now there is an option "Remove NPCs" which allows to "delete" both guards and civilians.

While this feature is useful, I'd rather only be able to delete them one at a time at my discretion. Thanks for looking into this!

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
