### ISSUE TITLE
suggest 

### ISSUE THREAD

**Issue by lemmonPickle** [pierre-josselin/payday-2-ultimate-trainer-5#85]
so I joined a lobby and they were at the end of the heist I was switching my builds before I pressed ready  " not ready " the host forced me to join and drop in with his mod without me pressing ready also he took me to custody and get me downed and get me out of custody I guess it is troll menu 

my suggestion is there a way to put the force spawn thing also the troll or counter to it and I was wondering if is it possible to make some or all host future to clint also because I see a lot of mods do that without getting the cheat tag and my last suggest I do not think it is possible but I should ask is there a way to delete something like keycards or loot or objects from the map like the removing packages you have in the mod

**Comment by pierre-josselin** [comment]
Hi, thank you for your suggestions.

About the force spawn it's already in ultimate trainer, you can found "start the heist" under the "instant menu"

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
