### ISSUE TITLE
Crash ( Damage Multiplier )

### ISSUE THREAD

**Issue by BMN1337** [pierre-josselin/payday-2-ultimate-trainer-5#86]
First, thank you for this mod.
///
"enable_damage_multiplier":true,"damage_multiplier":true

Gets saved in **ut-settings.json**. 
In dexterity menu damage multiplier is set to false on new heist ( set to true from settings file ) ,  but multiplier value is back at 0.0 which causes a crash to occur when player deals damage.
/// **Crash Log**
Application has crashed: C++ exception
mods/UltimateTrainer5/classes/Dexterity.lua:386: attempt to perform arithmetic on upvalue 'multiplier' (a boolean value)
///
Either fix saving these 2 in **ut-settings.json** or make damage multiplier default value = 1.0

**Comment by pierre-josselin** [comment]
#84

**Comment by pierre-josselin** [comment]
Hi, thanks for the report, I'll look into it.

**Comment by pierre-josselin** [comment]
@TwilightKillerX maybe you know what's wrong ?

**Comment by TwilightKillerX** [comment]
Hey 👋, I've had a look at it and I think the values for the four slider-based dexterities aren't being loaded from the custom JSON:
```
function UT.Dexterity:setDamageMultiplier(value, multiplier)
    UT:setSetting("enable_damage_multiplier", value)
    UT:setSetting("damage_multiplier", multiplier)
    UT:updateJsonValue("dexterity", "enable_damage_multiplier", value)
    UT:updateJsonValue("dexterity", "damage_multiplier", multiplier)

    _G.CloneClass(CopDamage)
    if value then
        function CopDamage:damage_bullet(attack_data)
            if attack_data.attacker_unit == managers.player:player_unit() then
                attack_data.damage = multiplier * 10
            end
            return self.orig.damage_bullet(self, attack_data)
        end

        function CopDamage:damage_melee(attack_data)
            if attack_data.attacker_unit == managers.player:player_unit() then
                attack_data.damage = multiplier * 10
            end
            return self.orig.damage_melee(self, attack_data)
        end
    else
        CopDamage.damage_bullet = CopDamage.orig.damage_bullet
        CopDamage.damage_melee = CopDamage.orig.damage_melee
    end
end
```
Even when we write toggle and multiplier values into `UT.modPath .. "/menus/" .. _json .. ".json"`, they get replaced by the defaults located in `dexterity.json`. That's odd! 

Come to think of it, none of my changes are being saved now 🤔

**Comment by pierre-josselin** [comment]
@TwilightKillerX Thank you for infos, i will look at this

**Comment by pierre-josselin** [comment]
Hi, I think it's fixed, please download the update from GitHub.
Let me know if a problem still occurs.
