### ISSUE TITLE
Crash ( God Mode )

### ISSUE THREAD

**Issue by BMN1337** [pierre-josselin/payday-2-ultimate-trainer-5#88]
Application has crashed: C++ exception
mods/UltimateTrainer5/classes/Dexterity.lua:26: attempt to index a nil value

SCRIPT STACK

at_exit() @mods/UltimateTrainer5/hooks/lib/states/ingamewaitingforplayersstate.lua:5
trans_func() lib/states/gamestate.lua:14
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:957
end_update() lib/setups/gamesetup.lua:865
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:600

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

God mode is set to false, crash occured after I tried to drop-in in crime spree lobby.Tried 2 times in the same lobby, other lobby worked fine.

**Comment by pierre-josselin** [comment]
Hi, does disabling the damage multiplier under the dexterity menu fixes the problem?

**Comment by pierre-josselin** [comment]
Hi, I think it's fixed, please download the update from GitHub.
Let me know if a problem still occurs.

**Comment by pierre-josselin** [comment]
Hi, I think it's fixed, please download the update from GitHub.
Let me know if a problem still occurs.

**Comment by BMN1337** [comment]
Just got the same crash log on the newest version.
Tried to drop-in after joining.
I removed **ut-settings.json** before updating and didn't use god mode at all.

**Comment by pierre-josselin** [comment]
Tried something new to fix this

**Comment by BMN1337** [comment]
Same conditions, same lobby too.
///
Application has crashed: C++ exception
mods/UltimateTrainer5/classes/Dexterity.lua:73: attempt to index local 'player' (a nil value)



SCRIPT STACK

at_exit() @mods/UltimateTrainer5/hooks/lib/states/ingamewaitingforplayersstate.lua:7
trans_func() lib/states/gamestate.lua:14
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:957
end_update() lib/setups/gamesetup.lua:865
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:600


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

**Comment by pierre-josselin** [comment]
Updated, can you download and try again and send new crashlog?
Sorry for the inconvenience.

**Comment by BMN1337** [comment]
No crash when we started from lobby, but happened when I reconnected and tried to drop-in.
///
Application has crashed: C++ exception
mods/UltimateTrainer5/classes/Dexterity.lua:219: attempt to index local 'player' (a nil value)



SCRIPT STACK

at_exit() @mods/UltimateTrainer5/hooks/lib/states/ingamewaitingforplayersstate.lua:15
trans_func() lib/states/gamestate.lua:14
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:957
end_update() lib/setups/gamesetup.lua:865
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:600


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

**Comment by pierre-josselin** [comment]
I dont know why but you cannot access `managers.player` or `managers.player:player_unit()`
I will continue the investigation.

**Comment by BMN1337** [comment]
Also got this one, right after joining.
///
Application has crashed: C++ exception
mods/UltimateTrainer5/classes/Dexterity.lua:219: attempt to index local 'player' (a nil value)



SCRIPT STACK

at_exit() @mods/UltimateTrainer5/hooks/lib/states/ingamewaitingforplayersstate.lua:15
trans_func() lib/states/gamestate.lua:14
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:957
end_update() lib/setups/gamesetup.lua:865
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:600


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

**Comment by pierre-josselin** [comment]
Untested solution attempt

```
function UT.Dexterity:setGodMode(value, --[[optional]]showAlert)
    if type(value) ~= "boolean" then
        return
    end

    UT:setSetting("enable_god_mode", value)
    UT:updateJsonValue("dexterity", "ut_item_dexterity_toggle_god_mode", value)
    
    local player = managers.player and managers.player:player_unit()
    if not alive(player) then
        --! player does not exist yet, queue godmode state
        Global.god_mode = value
        return
    end
    
    player:character_damage():set_god_mode(value)


    if showAlert == false then
        return
    end

    if value then
        UT:addAlert("ut_alert_god_mode_enabled", UT.colors.success)
    else
        UT:addAlert("ut_alert_god_mode_disabled", UT.colors.success)
    end
end
```

By _atom

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
