### ISSUE TITLE
crashing when shooting someone

### ISSUE THREAD

**Issue by mejbu** [pierre-josselin/payday-2-ultimate-trainer-5#89]
KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 1218

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 64192

    Key  : Analysis.Init.CPU.mSec
    Value: 342

    Key  : Analysis.Init.Elapsed.mSec
    Value: 51376

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 102

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 75200

    Key  : Timeline.Process.Start.DeltaSec
    Value: 75

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z

    Key  : WER.OS.Version
    Value: 10.0.19041.1

FILE_IN_CAB:  payday2_win32_release_4050501_crash_2022_9_27T14_33_34C0.mdmp

COMMENT:  Application has crashed: C++ exception
mods/UltimateTrainer5/classes/Dexterity.lua:386: attempt to perform arithmetic on upvalue 'multiplier' (a boolean value)

SCRIPT STACK

give_impact_damage() lib/units/weapons/raycastweaponbase.lua:2239
on_collision() lib/units/weapons/raycastweaponbase.lua:2152
_fire_raycast() lib/units/weapons/raycastweaponbase.lua:709
fire() lib/units/weapons/raycastweaponbase.lua:479
trigger_held() lib/units/weapons/raycastweaponbase.lua:391
_check_action_primary_attack() lib/units/beings/player/states/playerstandard.lua:4850
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:948
update() lib/units/beings/player/states/playerstandard.lua:435
original() lib/units/beings/player/playermovement.lua:272
@mods/base/req/core/Hooks.lua:288

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                             

CONTEXT:  (.ecxr)
eax=0019d7d8 ebx=00000000 ecx=00000003 edx=00000000 esi=0019db58 edi=0019f79c
eip=775bcc12 esp=0019d7d8 ebp=0019d830 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000216
KERNELBASE!RaiseException+0x62:
775bcc12 8b4c2454        mov     ecx,dword ptr [esp+54h] ss:002b:0019d82c=eb3d0a93
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 775bcc12 (KERNELBASE!RaiseException+0x00000062)
   ExceptionCode: e06d7363 (C++ EH exception)
  ExceptionFlags: 00000001
NumberParameters: 3
   Parameter[0]: 19930520
   Parameter[1]: 0019f784
   Parameter[2]: 00a93218

PROCESS_NAME:  payday2_win32_release.exe

ERROR_CODE: (NTSTATUS) 0xe06d7363 - <Unable to get error code text>

EXCEPTION_CODE_STR:  e06d7363

EXCEPTION_PARAMETER1:  19930520

EXCEPTION_PARAMETER2:  0019f784

EXCEPTION_PARAMETER3:  00a93218

STACK_TEXT:  
0019d830 009a203a     e06d7363 00000001 00000003 KERNELBASE!RaiseException+0x62
WARNING: Stack unwind information not available. Following frames may be wrong.
0019d868 006bac06     0019f784 00a93218 009b2f07 payday2_win32_release!zip_get_name+0x10065a
0019f7a8 00837426     00000001 03204000 00000001 payday2_win32_release+0x2bac06
0019f828 00838d11     0099a3cf 00000001 0019fef4 payday2_win32_release+0x437426
0019f82c 0099a3cf     00000001 0019fef4 00000000 payday2_win32_release+0x438d11
0019f904 778a5db7     00cd21bc 02d88280 00000001 payday2_win32_release!zip_get_name+0xf89ef
0019fc44 778d2ccc     775b7abe ffffffff 009afc0c ntdll!RtlpDosPathNameToRelativeNtPathName+0x427
0019fc6c 775b7a2e     ffffffff 009afc0c 0019fcac ntdll!NtQueryVirtualMemory+0xc
0019fd44 005c0029     00610070 00640079 00790061 KERNELBASE!BasepFillUEFInfo+0x1d
0019fda8 00819ea0     0019fefc 778dae00 8fa2e32b payday2_win32_release+0x1c0029
0019fdc0 778a2937     02ac3290 00000400 00000200 payday2_win32_release+0x419ea0
0019fe6c 00819f9b     00ae974c 00000270 778c4e50 ntdll!RtlpReAllocateHeapInternal+0xf7
0019fea4 775a451b     778bac49 0019feb8 0019fefc payday2_win32_release+0x419f9b
0019febc 009ad08c     f82dd84b 0019feec 009a3a80 KERNELBASE!FlsGetValue+0x1b
0019fec8 009a3a80     00000000 00000000 0019fefc payday2_win32_release!zip_get_name+0x10b6ac
0019feec 009c2e4e     0019ff20 008374f2 0099a3cf payday2_win32_release!zip_get_name+0x1020a0
0019fef4 008374f2     0099a3cf 00000001 00000000 payday2_win32_release!zip_get_name+0x12146e
0019ff20 00836ed5     0099a4d6 00400000 00000000 payday2_win32_release+0x4374f2
0019ff70 76c8fa29     00226000 76c8fa10 0019ffdc payday2_win32_release+0x436ed5
0019ff80 778c7b5e     00226000 f82dd927 00000000 kernel32!BaseThreadInitThunk+0x19
0019ffdc 778c7b2e     ffffffff 778e8c87 00000000 ntdll!__RtlUserThreadStart+0x2f
0019ffec 00000000     0099a3cf 00226000 00000000 ntdll!_RtlUserThreadStart+0x1b

STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_NAME:  payday2_win32_release+10065a

MODULE_NAME: payday2_win32_release

IMAGE_NAME:  payday2_win32_release.exe

FAILURE_BUCKET_ID:  CPP_EXCEPTION_e06d7363_payday2_win32_release.exe!Unknown

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x86

OSNAME:  Windows 10

FAILURE_ID_HASH:  {6348ce8c-82ad-e872-feb1-ce793facaa3a}

**Comment by mejbu** [comment]
just to clarify, doing any kind of damage to the AI will crash the game

**Comment by pierre-josselin** [comment]
Hi, I think it's fixed, please download the update from GitHub.
Let me know if a problem still occurs.
