### ISSUE TITLE
Set Spawn point?

### ISSUE THREAD

**Issue by WingsOfCoronia** [pierre-josselin/payday-2-ultimate-trainer-5#91]
What does this even do? I thought it spawn NPCs or Civilians as it said but when i look at the ground and "set spawn point NPCs/Civilians" it literally does nothing?

**Comment by pierre-josselin** [comment]
Here's how it works:

1. Choose the spawn position (it can be on you -self- or where you are looking -crosshair-)
2. Choose the type of unit to spawn (civilians, allies, enemies, loot...)
3. Use the mouse wheel up and down to select the unit
4. Use the mouse wheel button to spawn the unit

**Comment by WingsOfCoronia** [comment]
> Here's how it works:
> 
> 1. Choose the spawn position (it can be on you -self- or where you are looking -crosshair-)
> 2. Choose the type of unit to spawn (civilians, allies, enemies, loot...)
> 3. Use the mouse wheel up and down to select the unit
> 4. Use the mouse wheel button to spawn the unit

![20221024234748_1](https://user-images.githubusercontent.com/98377172/197581921-373ce562-c6e9-4a50-9455-9399512747cd.jpg)
this is the picture of the "Set Spawn Point",i already done what you've said but nothing? I can't see anything to do with the mousewheel too, they just doesn't exist???

**Comment by pierre-josselin** [comment]
Once you have selected a spawn mode, go back to the game and use your mouse wheel to scroll through the units and your click on your mouse wheel button to spawn the unit. If nothing happens with the mouse wheel, go to the mods keybinds settings and check the keys (you can use any key on the keyboard instead of the mouse wheel).

**Comment by WingsOfCoronia** [comment]
> Once you have selected a spawn mode, go back to the game and use your mouse wheel to scroll through the units and your click on your mouse wheel button to spawn the unit. If nothing happens with the mouse wheel, go to the mods keybinds settings and check the keys (you can use any key on the keyboard instead of the mouse wheel).

Got it! Thanks for the whole explaination :D
