### ISSUE TITLE
Crashing when online

### ISSUE THREAD

**Issue by TinyCoderJay** [pierre-josselin/payday-2-ultimate-trainer-5#92]
When joining an online game it crashes everytime.

**Comment by pierre-josselin** [comment]
For your information, this can happen when you use detected cheats (such as unlocked DLC content or skill points) and try to join a lobby where cheaters are kicked (which is enabled by default).

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
