### ISSUE TITLE
Crash when entering multiplayer game

### ISSUE THREAD

**Issue by yexum** [pierre-josselin/payday-2-ultimate-trainer-5#94]
Application has crashed: C++ exception
mods/UltimateTrainer5/classes/Dexterity.lua:219: attempt to index local 'player' (a nil value)

SCRIPT STACK

at_exit() @mods/UltimateTrainer5/hooks/lib/states/ingamewaitingforplayersstate.lua:15
trans_func() lib/states/gamestate.lua:14
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:957
end_update() lib/setups/gamesetup.lua:868
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:600

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap

**Comment by pierre-josselin** [comment]
Hi, I'm not currently working on the mod but I'll keep the issue open if anyone has a solution.

**Comment by pierre-josselin** [comment]
For your information, this can happen when you use detected cheats (such as unlocked DLC content or skill points) and try to join a lobby where cheaters are kicked (which is enabled by default).

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
