### ISSUE TITLE
Menu or options isn't anywhere

### ISSUE THREAD

**Issue by NotorietyEDF** [pierre-josselin/payday-2-ultimate-trainer-5#96]
I have followed all the steps of the instructions and I can't find the menu whether in a heist or in the menu. Could someone help me with this? Maybe I installed it wrong?

**Comment by pierre-josselin** [comment]
Hi, please send a picture of your "mods" folder

**Comment by NotorietyEDF** [comment]
![image_2022-12-13_194758979](https://user-images.githubusercontent.com/120429463/207485018-e5973483-a10a-4de7-8c65-7f0fa94efe67.png)

**Comment by pierre-josselin** [comment]
Ok so inside "payday-2-ultimate-trainer-5-main", there is a folder named "UltimateTrainer5".
Take out "UltimateTrainer5" to put it in "mods" folder and it will work.

**Comment by NotorietyEDF** [comment]
Thank you, it worked now.
