### ISSUE TITLE
Multiplayer crash issue again

### ISSUE THREAD

**Issue by Qelks** [pierre-josselin/payday-2-ultimate-trainer-5#97]
I tried joining multiplayer but it keeps crashing everytime, couldn't find the reason

**Comment by Respawn-ID** [comment]
Try to reinstall the mod and the game
And remove other mod u had installed

**Comment by pierre-josselin** [comment]
Closed as Ultimate Trainer 6 is released:
https://github.com/pierre-josselin/payday-2-ultimate-trainer-6
