### ISSUE TITLE
not launching

### ISSUE THREAD

**Issue by GHDavor** [pierre-josselin/payday-2-ultimate-trainer-5#98]
this trainer broke the game and i cannot enter the game anymore, i deleted evey mod i had, also the trainer, and still, it doesn't launch, it doesn't even generate a crash log. Help please

**Comment by pierre-josselin** [comment]
Hi, the problem you are experiencing cannot be caused by this mod since it does not alter any game files.
I advise you to try to delete the file WSOCK32.dll or IPHLPAPI.dll and run a verification of the integrity of the game through steam.
